imc1():- write('Digite seu nome: '),
    	read(X),
    	nl,
    	write('Digite seu peso: '),
    	read(P),
    	nl,
    	write('Digite sua altura: '),
    	read(H),
    	I is P/H^2,
    	nl,
    	write(X),
    	write(', seu imc eh: '),
    	write(I).
