dono(jose, carro(onix, azul, passeio)).
dono(ana, carro(fiesta, vermelho, hatchback)).
dono(pedro, carro(civic, prata, sedan)).
dono(maria, carro(corolla, preto, sedan)).
dono(fernando, carro(gol, branco, hatchback)).
dono(beatriz, carro(uno, amarelo, hatchback)).
dono(joao, carro(polo, cinza, hatchback)).
dono(rita, carro(fox, vermelho, hatchback)).
dono(carlos, carro(etios, verde, sedan)).
dono(leticia, carro(ka, prata, hatchback)).
